version: '3.7'

services:

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - mariadb
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:80
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/virgool
    environment:
      XDEBUG_CONFIG: remote_host=$XDEBUG_REMOTE_HOST
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        /* Enable non minified asset files */
        define( 'SCRIPT_DEBUG', true );
        /* Make WordPress install plugins directly */
        define( 'FS_METHOD', 'direct' );
        /* Set default language to Persian */
        define( 'WPLANG', 'fa_IR' );

  wordpress-cli:
    depends_on:
      - mariadb
      - wordpress
    image: wordpress:cli
    user: xfs
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/virgool
    command:
      - --info

volumes:
  wordpress:

networks:
  default:
    external: true
    name: localnet
